//! The session flows behind a thread's context menu (`docs/12` §2.3).
//!
//! Eight commands that are all *decisions* rather than pass-throughs, which is why they
//! live here and not in `bridge.rs`: each one either re-reads something the engine does
//! not announce, moves state the host owns, chooses a path the engine must not choose, or
//! refuses input in the host so the UI never round-trips it. The measurement behind each
//! is quoted where it decides the shape:
//!
//! | flow | the engine fact it is built on |
//! | --- | --- |
//! | rename | a bare ack, no event and no echo of the name |
//! | fork targets | `get_branch_messages` is the only source of valid entry ids |
//! | fork | a new session **in the same sidecar**; the response carries no identity |
//! | handoff | a compaction entry, never a file (`savedPath` is auto-path only) |
//! | export | with no `outputPath` the file lands in the *sidecar's* cwd |
//! | open | nothing is opened that the app is not already showing |
//! | delete | `delete` is not an advertised command at all |
//! | pin | the engine holds a cross-process lock on the pin file |
//!
//! Every function here takes plain values rather than Tauri state, so the decisions can
//! be exercised without a window — the live test (`tests/flows.rs`) drives exactly what
//! the commands drive.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use omp_store::Store;
use omp_transport::protocol::commands;
use omp_transport::OmpClient;

use crate::dto::BranchTarget;
use crate::session::{self, ActivitySink, LiveSession};
use crate::threads::Threads;

/// The directory the app's exports live in, under its own config directory.
///
/// The app's, not the engine's: nothing upstream writes here, so an export cannot be
/// mistaken for a session file by the catalogue, and `open_path` gets a directory it can
/// allow in its entirety without reasoning about what else is in it.
pub const EXPORTS_DIR: &str = "exports";

/// How long the engine gets for a fork.
///
/// A fork is a session transition on the engine's side — it flushes the current file,
/// mints a new one, rewrites its message list and reloads it — and its answer is the only
/// thing that says the transition happened. Bounded rather than left to the transport's
/// default so a transition that never completes surfaces as an error instead of a UI that
/// waits forever on a thread that no longer exists.
const FORK_TIMEOUT: Duration = Duration::from_secs(60);

/// How long the engine gets for a handoff.
///
/// Minutes, not seconds, and deliberately not the transport's default (20 s): the handoff
/// document is *generated by the model* over the compacted context, so the engine's answer
/// is a model call. A shorter bound would report a failure for a handoff that went on to
/// commit — the worst of both, since the session is compacted either way.
const HANDOFF_TIMEOUT: Duration = Duration::from_secs(300);

/// The engine's own refusal for a name that is empty once trimmed, quoted.
///
/// The RPC handler trims first and then answers exactly this (measured: `{success: false,
/// error: "Session name cannot be empty"}`, with no `code`), so refusing the same input
/// with the same words in the host is the same answer without the round trip — and the
/// window shows the engine's sentence either way.
const EMPTY_NAME: &str = "Session name cannot be empty";

/// Rename the session, then re-read what the chrome renders.
///
/// Measured at v18.2.6: `set_session_name` answers a bare ack and emits **nothing** — no
/// `session_info_update`, no title event, and the ack does not echo the name — so nothing
/// will arrive to correct a stale one. What the engine did do is rewrite the session
/// file's title slot in place, which is why the rename also shows up in the catalogue once
/// the sidebar re-reads it (the caller's business, not this function's).
pub async fn rename(live: &LiveSession, name: &str) -> Result<(), String> {
    let name = name.trim();
    if name.is_empty() {
        return Err(EMPTY_NAME.to_string());
    }

    let client = client(live)?;
    session::send(&client, commands::set_session_name(name), "rename").await?;

    // The refresh is not allowed to fail the rename: the name *is* set, and reporting a
    // failure for it would be a lie about a change that happened. A missed refresh is a
    // stale chip, which is what `reread_control` is for.
    refresh(live).await;

    Ok(())
}

/// The user messages a fork can start from.
///
/// The only source of valid `entryId`s, measured: `get_messages` and `get_messages_page`
/// carry none (the page cursor hides the leaf id), so a picker built from the transcript
/// would have nothing valid to send — and a bad id is not an answer but a *throw*
/// (`Invalid entry ID for branching`).
pub async fn branch_targets(live: &LiveSession) -> Result<Vec<BranchTarget>, String> {
    let client = client(live)?;
    let response = session::call(
        &client,
        commands::get_branch_messages(),
        None,
        "branch target list",
    )
    .await?;

    serde_json::from_value(response["data"]["messages"].clone()).map_err(|error| {
        format!("the agent's branch messages were not `{{entryId, text}}` rows: {error}")
    })
}

/// Fork the session at one of its user messages, returning the new thread's row.
///
/// The engine branches **in place**: `branch` mints a new session file in the same
/// sidecar, the old id stops existing, and the response is `{text, cancelled}` — it says
/// nothing about identity (measured). So the new id comes from a fresh `get_state`, the
/// registry entry moves with it, and the conversation is re-read because the engine
/// replaces its own message list without replaying anything over the event stream.
///
/// The registry and the identity move *before* the transcript is re-read: both are facts
/// about the engine that are already true, and a slow (or failing) history read must not
/// leave the sidebar pointing at an id nothing answers to.
pub async fn branch(
    threads: &Threads,
    sink: &impl ActivitySink,
    live: &Arc<LiveSession>,
    entry_id: &str,
) -> Result<crate::dto::ThreadSnapshot, String> {
    let client = client(live)?;
    let from = live.thread.current();

    // Validated against the engine's own list before it is sent, rather than relying on
    // the failure coming back: the handler `throw`s on an unknown id, and a handler that
    // throws is not guaranteed to answer at all (measured at v18.2.6 the serial
    // dispatcher does answer `{success: false}` for it, but nothing in the protocol
    // promises that, and a fork that hangs is a window that cannot be used).
    let targets = branch_targets(live).await?;
    if !targets.iter().any(|target| target.entry_id == entry_id) {
        return Err(format!(
            "`{entry_id}` is not one of the {} messages this session can fork at",
            targets.len()
        ));
    }

    let response = session::call(
        &client,
        commands::branch(entry_id),
        Some(FORK_TIMEOUT),
        "fork",
    )
    .await?;

    // A vetoed fork (`session_before_branch` from an extension) leaves the session exactly
    // where it was, so nothing below may run: re-reading and re-keying would file the
    // *old* session under itself and hydrate a conversation that did not change.
    if response["data"]["cancelled"].as_bool() == Some(true) {
        return Err("the engine cancelled the fork (an extension vetoed it)".to_string());
    }

    // The only carrier of the new identity, and the same read the handshake does.
    let control = live.reread_control().await.map_err(|error| {
        format!("the fork happened, but the session it moved to could not be read: {error}")
    })?;
    let to = control.session_id;
    live.thread.set(to.clone());
    threads.refile(&from, Arc::clone(live));
    threads.publish(sink);

    session::hydrate(&client, &live.transcript)
        .await
        .map_err(|error| {
            format!("forked to {to}, but its conversation could not be read: {error}")
        })?;

    Ok(live.snapshot())
}

/// Hand the session over, reporting the engine's refusals.
///
/// Not an export and not a new session: measured, the document is committed as a
/// compaction entry **into this session** and no file is written — `savedPath` is only
/// assigned on the auto-triggered path, which RPC never takes, so the response's `data` is
/// `{savedPath: undefined}` at best. What moves is the context usage, which is why the
/// control snapshot is re-read here; the transcript is the caller's to re-read, since the
/// maintenance becomes rows rather than a patch this command can address.
///
/// The engine refuses in prose and without a `code` — mid-turn ("Cannot hand off while a
/// response is in progress"), "Nothing to hand off (no messages yet)", "Nothing to hand off
/// (already compacted)", "No model selected for handoff" — so every one of them is
/// surfaced as an error the UI shows verbatim.
pub async fn handoff(live: &LiveSession, instructions: Option<&str>) -> Result<(), String> {
    let client = client(live)?;
    session::call(
        &client,
        commands::handoff(instructions),
        Some(HANDOFF_TIMEOUT),
        "handoff",
    )
    .await?;

    refresh(live).await;

    Ok(())
}

/// The path the app exports a session to, under its own directory.
///
/// Named after the session id rather than after the session *file*: the engine's own
/// default names the file's stem, and it is the one part of its choice worth keeping —
/// a person looking at two exports needs to know which conversation each one is.
pub fn export_path(exports: &Path, session_id: &str) -> PathBuf {
    exports.join(format!("omp-session-{session_id}.html"))
}

/// Write the conversation out as HTML, under the app's own config directory.
///
/// The path is the host's, and it has to be: measured, `export_html` with no `outputPath`
/// writes `omp-session-<stem>.html` **relative to the sidecar's working directory** —
/// `Bun.write` resolves it, and the sidecar's cwd is the user's project. So the app names
/// an absolute path inside `<config dir>/exports` and returns the path the engine answered
/// with, rather than the one it asked for: an engine that wrote somewhere else is a fact
/// worth reporting, not something to paper over.
pub async fn export(live: &LiveSession, config_dir: Option<&Path>) -> Result<String, String> {
    let exports = exports_dir(config_dir).ok_or_else(|| {
        "the app has no config directory, so there is nowhere to write an export".to_string()
    })?;

    std::fs::create_dir_all(&exports).map_err(|error| {
        format!(
            "the export directory {} could not be created: {error}",
            exports.display()
        )
    })?;

    let path = export_path(&exports, &live.thread.current());
    let path_text = path
        .to_str()
        .ok_or_else(|| format!("{} is not a valid UTF-8 path", path.display()))?;

    let client = client(live)?;
    let response = session::call(
        &client,
        commands::export_html(Some(path_text)),
        None,
        "export",
    )
    .await?;

    response["data"]["path"]
        .as_str()
        .map(str::to_string)
        .ok_or_else(|| format!("the agent's export answer carried no path: {response}"))
}

/// The app's export directory, when the platform gave it a config directory to live in.
pub fn exports_dir(config_dir: Option<&Path>) -> Option<PathBuf> {
    config_dir.map(|dir| dir.join(EXPORTS_DIR))
}

/// What `open_path` will hand to the system, and nothing else.
///
/// A value rather than a list of parameters because the decision has exactly one shape: an
/// absolute, existing path may be opened when it is inside the app's own export directory
/// or *is* a directory the app is already showing. Built once per call from what is on
/// screen, so the part worth reviewing is a function of two paths.
///
/// Why an allowlist at all: this command exists so a path from the conversation can reach
/// the user's desktop, and a path is a request to launch whatever the system associates
/// with it. `file:` is refused by [`crate::external`] for exactly that reason (its
/// allowlist is for the web), so the two commands are deliberately different doors with
/// different rules.
pub struct Allowlist {
    /// The app's own export directory: the one place a path may be *inside* of.
    exports: Option<PathBuf>,
    /// The workspaces the app is showing the *contents* of: every live thread's, because
    /// the right panel's Tree view (`docs/12` §8.2) lists them one level at a time and a
    /// row's click has to open the file it names.
    ///
    /// Inside, at any depth — and that is the difference from [`Allowlist::shown`], which
    /// is equality only. The rule is a statement about what is on screen: a live thread's
    /// workspace is a tree the window is drawing, while the catalogue's directories are
    /// labels on rows nobody has opened. A session's *own* directory is not added here
    /// either: a closed session has no panel listing it, and widening the rule to "any
    /// directory a session was ever worked in" is the statement about the user's whole
    /// disk this allowlist exists to refuse.
    workspaces: Vec<PathBuf>,
    /// Directories the app is showing: every session the sidebar lists — the directory it
    /// was worked in, and the bucket its file sits in.
    ///
    /// Equality only, deliberately. "The app is showing this directory" is a statement
    /// about a directory, and widening it to "anything under a project the user ever
    /// opened" would make the allowlist a statement about the user's whole disk.
    shown: Vec<PathBuf>,
}

impl Allowlist {
    /// Collect what the host is showing: the live threads and the catalogue.
    pub fn collect(store: Option<&Store>, threads: &Threads, exports: Option<PathBuf>) -> Self {
        let mut shown: Vec<PathBuf> = Vec::new();
        let mut workspaces: Vec<PathBuf> = Vec::new();

        for thread in threads.snapshots() {
            if !thread.workspace.is_empty() {
                workspaces.push(PathBuf::from(thread.workspace));
            }
        }

        if let Some(store) = store {
            for session in store.list() {
                if !session.cwd.is_empty() {
                    shown.push(PathBuf::from(&session.cwd));
                }
                if let Some(bucket) = session.path.parent() {
                    shown.push(bucket.to_path_buf());
                }
            }
        }

        Self {
            exports,
            workspaces,
            shown,
        }
    }

    /// The canonical path this may be opened as, or the reason it may not.
    ///
    /// Split from [`Allowlist::open`] so the decision can be asserted without a desktop: a
    /// check that had to launch `xdg-open` to run is a check nobody runs.
    pub fn permit(&self, path: &str) -> Result<PathBuf, String> {
        let requested = Path::new(path.trim());

        // A scheme is not a path. `file:///etc/passwd` is refused here for the same reason
        // `external` refuses it: this command opens a filesystem location, and the URL
        // form is how such a thing arrives from somewhere it should not. (Being absolute
        // is the test — `file:///x` is not.)
        if !requested.is_absolute() {
            return Err(format!(
                "`{}` is not an absolute path, so the app will not open it",
                requested.display()
            ));
        }

        // Resolved before it is judged: `..` segments and symlinks are exactly how a path
        // that reads as allowed reaches somewhere else, so the comparison is made on what
        // the filesystem says the path *is*. Absent paths are refused here too, which is
        // the other half of the same rule — nothing can be opened that is not there.
        let resolved = requested
            .canonicalize()
            .map_err(|error| format!("`{}` cannot be opened: {error}", requested.display()))?;

        if self
            .exports
            .as_ref()
            .is_some_and(|exports| resolved.starts_with(resolved_or(exports)))
        {
            return Ok(resolved);
        }

        // Inside the workspace of a thread that is open: the Tree view's own rule, and
        // the reason a file row can be clicked at all. Both sides are resolved before they
        // are compared, so `..` and a symlink out of the workspace land on the refusal
        // below just as they do for the other two.
        if self
            .workspaces
            .iter()
            .any(|workspace| contains(workspace, &resolved))
        {
            return Ok(resolved);
        }

        if self
            .shown
            .iter()
            .any(|directory| same_directory(directory, &resolved))
        {
            return Ok(resolved);
        }

        Err(format!(
            "`{}` is not the app's export directory, a live thread's workspace, or a \
             directory it is showing",
            resolved.display()
        ))
    }

    /// Hand an allowed path to the system's default application.
    ///
    /// Detached, like [`crate::external::open`]: the app must not hold a file manager or a
    /// browser as a child, and must not wait for one to exit before its window responds.
    pub fn open(&self, path: &str) -> Result<(), String> {
        let resolved = self.permit(path)?;

        // The `Path` itself, not a string: a path that is not valid UTF-8 is still a path,
        // and rewriting it through `to_string_lossy` would open a file that does not exist.
        open::that_detached(&resolved)
            .map_err(|error| format!("could not open {}: {error}", resolved.display()))
    }
}

/// Delete a session: its file and its artifacts directory.
///
/// App-owned file removal, and there is no alternative: measured at v18.2.6, `delete` is
/// **not** among the 45 commands `get_available_commands` advertises (the engine's own
/// `/delete` is TUI-only), so there is nothing to dispatch. The id is resolved through the
/// catalogue rather than accepted as a path — a caller that could name a file to remove
/// would make this command a general-purpose delete.
///
/// A live thread with that id is refused rather than served, and that is the rule rather
/// than a courtesy: the sidecar holds the session open, so its next write recreates the
/// file it is appending to, and the user's delete would appear to have been undone by the
/// agent they were still talking to.
pub fn delete(store: Option<&Store>, threads: &Threads, id: &str) -> Result<(), String> {
    if threads.get(id).is_some() {
        return Err(format!(
            "session {id} is open in this window; close its thread before deleting it"
        ));
    }

    let store = store.ok_or_else(|| {
        "the engine's session store is not available, so a session cannot be deleted".to_string()
    })?;

    let session = store
        .find(id)
        .ok_or_else(|| format!("no session with id {id}"))?;

    std::fs::remove_file(&session.path)
        .map_err(|error| format!("{} was not removed: {error}", session.path.display()))?;

    // The artifacts directory is the file's own path with the suffix stripped, which is
    // the engine's rule (`artifactsDirectoryFor`) rather than a guess at a sibling: a
    // session's subagent transcripts live there, and leaving them behind would leave a
    // deleted conversation's contents on disk. The rule itself lives in
    // [`crate::panel`], which is the module that has to resolve an artifact to read it.
    if let Ok(artifacts) = crate::panel::artifacts_dir(&session.path.to_string_lossy()) {
        if artifacts.is_dir() {
            std::fs::remove_dir_all(&artifacts)
                .map_err(|error| format!("{} was not removed: {error}", artifacts.display()))?;
        }
    }

    // The file is gone, so nothing about this id is suspended any more — and a released
    // thread is exactly the case this path sees most, because a live one is refused above.
    // Leaving the mark would keep a deleted session's row drawn as released if the id ever
    // came back.
    threads.clear_suspension(id);

    // If the directory that contained this session is now empty, remove it so ghost project
    // folders do not linger in ~/.omp/agent/sessions/.
    if let Some(parent) = session.path.parent() {
        let _ = std::fs::remove_dir(parent);
    }

    Ok(())
}

/// Pin or unpin a session through the engine's own `/pin <id>`.
///
/// Dispatched as a *prompt*, which is the only safe way to write the pin set: measured,
/// the engine holds a native cross-process lock on `session-pins.json` (abstract Unix
/// sockets on Linux) while it rewrites it, so an app that wrote the JSON itself would be
/// guessing at OMP's ordering. `pin` is one of the advertised builtins and the RPC prompt
/// handler dispatches builtins before the model (`executeAcpBuiltinSlashCommand`), so this
/// costs a local command and no turn — the confirmation arrives as a `command_output`
/// frame, which the pump already turns into a notice row.
///
/// An empty id is refused in the host: `/pin` with no argument pins *the session it was
/// dispatched through*, which is a different action from the one the caller asked for.
pub async fn pin(live: &LiveSession, id: &str) -> Result<(), String> {
    let id = id.trim();
    if id.is_empty() {
        return Err("no session id to pin".to_string());
    }

    let client = client(live)?;
    session::send(
        &client,
        commands::prompt(format!("/pin {id}"), &[], None),
        "pin",
    )
    .await
}

/// Re-read the control snapshot after an accepted command, letting a miss pass.
///
/// A refresh here is an optimisation for coherence — the change itself has already
/// happened on the engine's side — so a failure must not be reported as a failed command.
/// It is logged rather than dropped: a *silent* miss is how a stale name becomes
/// unexplainable the next time someone asks why the row disagrees with the session.
async fn refresh(live: &LiveSession) {
    if let Err(error) = live.reread_control().await {
        eprintln!("[omp-desktop] could not refresh session state: {error}");
    }
}

/// The live session a flow acts on, or the reason it cannot.
fn client(live: &LiveSession) -> Result<Arc<OmpClient>, String> {
    live.client()
        .ok_or_else(|| "the session is shutting down".to_string())
}

/// Whether two paths name the same directory.
///
/// The requested path is already canonical, so the comparison is against the candidate as
/// written first — which is what the catalogue holds, and the case that hits. Only a miss
/// pays for a `stat`: a session list is thousands of rows, and resolving every one of them
/// on every click is work nobody asked for. The fallback is not optional though: `/tmp` and
/// `/private/tmp` on macOS are the same directory under two names, and which one a session
/// recorded is the engine's business.
/// Whether `resolved` is inside `directory` (or is it).
///
/// The directory is resolved too, because a workspace can itself be reached through a
/// symlink (a project under `/tmp` on a platform where `/tmp` is one), and comparing a
/// resolved child against an unresolved root would refuse every path in it.
fn contains(directory: &Path, resolved: &Path) -> bool {
    resolved.starts_with(resolved_or(directory))
}

fn same_directory(candidate: &Path, resolved: &Path) -> bool {
    candidate == resolved || candidate.canonicalize().is_ok_and(|it| it == resolved)
}

/// A directory as the filesystem resolves it, or as written when it does not exist yet.
///
/// The export directory is created by the export flow, so a path inside it is only ever
/// compared once it exists; a root that does not exist cannot contain anything, and
/// falling back to the text keeps the check honest instead of failing it open.
fn resolved_or(path: &Path) -> PathBuf {
    path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A directory tree under the temp dir, removed and recreated per test.
    fn workspace(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!("omp-desktop-flows-{name}"));
        let _ = std::fs::remove_dir_all(&path);
        std::fs::create_dir_all(&path).expect("the test directory");
        path
    }

    /// The allowlist admits exactly three things, and a path is opened only once it is one
    /// of them.
    ///
    /// This is the app's whole exposure to the desktop: everything else the frontend can
    /// reach is a command with an engine answer behind it. The cases that matter are the
    /// near misses — a *sibling* of the export directory, an escape through `..` inside a
    /// shown directory, and the `file:` URL the sibling command refuses.
    #[test]
    fn only_the_export_directory_and_the_shown_directories_may_be_opened() {
        let root = workspace("allowlist");
        let exports = root.join("config/exports");
        let project = root.join("project");
        let outside = root.join("outside");
        for dir in [&exports, &project, &outside] {
            std::fs::create_dir_all(dir).expect("a directory");
        }
        let exported = exports.join("omp-session-abc.html");
        std::fs::write(&exported, "<html></html>").expect("an export");

        let allowlist = Allowlist {
            exports: Some(exports.clone()),
            workspaces: Vec::new(),
            shown: vec![project.clone()],
        };

        // Inside the app's own export directory, at any depth.
        assert!(allowlist.permit(&exported.display().to_string()).is_ok());
        assert!(allowlist.permit(&exports.display().to_string()).is_ok());

        // The directory the app is showing.
        assert!(allowlist.permit(&project.display().to_string()).is_ok());

        // A file *inside* a shown directory is not the directory the app is showing.
        let loose = project.join("notes.txt");
        std::fs::write(&loose, "hi").expect("a file");
        assert!(allowlist.permit(&loose.display().to_string()).is_err());

        // A sibling whose name merely starts with the export directory's.
        std::fs::create_dir_all(root.join("config/exports-evil")).expect("a sibling");
        let evil = root.join("config/exports-evil/x.html");
        std::fs::write(&evil, "x").expect("a file");
        assert!(allowlist.permit(&evil.display().to_string()).is_err());

        // An escape that reads as inside a shown directory but resolves outside it.
        let escape = project.join("../outside/secret.txt");
        std::fs::write(&escape, "x").expect("a file");
        assert!(allowlist.permit(&escape.display().to_string()).is_err());

        // Anything else: a scheme instead of a path, a relative path, and a path that is
        // not there.
        assert!(allowlist.permit("file:///etc/passwd").is_err());
        assert!(allowlist.permit("notes.txt").is_err());
        assert!(allowlist
            .permit(&root.join("gone/away.txt").display().to_string())
            .is_err());
    }

    /// A live workspace is the one place a path may be opened from *inside*.
    ///
    /// The Tree view (`docs/12` §8.2) lists a live thread's workspace and every file row in
    /// it is a click, so `open_path` has to admit what is under it — and nothing else: the
    /// sibling directory, the escape through `..`, and the workspace of a session that is
    /// not open are all still refusals.
    #[test]
    fn a_file_inside_a_live_workspace_may_be_opened() {
        let root = workspace("workspace-allowlist");
        let project = root.join("project");
        let sibling = root.join("elsewhere");
        for dir in [&project, &sibling] {
            std::fs::create_dir_all(dir).expect("a directory");
        }
        let file = project.join("src/main.rs");
        std::fs::create_dir_all(project.join("src")).expect("a directory");
        std::fs::write(&file, "fn main() {}").expect("a file");

        let allowlist = Allowlist {
            exports: None,
            workspaces: vec![project.clone()],
            shown: Vec::new(),
        };

        // The workspace itself, and anything under it, at any depth.
        assert!(allowlist.permit(&project.display().to_string()).is_ok());
        assert!(allowlist.permit(&file.display().to_string()).is_ok());

        // A sibling that merely shares a prefix is not inside it.
        std::fs::create_dir_all(root.join("project-evil")).expect("a sibling");
        let evil = root.join("project-evil/x.txt");
        std::fs::write(&evil, "x").expect("a file");
        assert!(allowlist.permit(&evil.display().to_string()).is_err());

        // And nothing climbs out of it.
        let escape = project.join("../elsewhere/secret.txt");
        std::fs::write(&escape, "x").expect("a file");
        assert!(allowlist.permit(&escape.display().to_string()).is_err());
    }

    /// A path is refused when it is a *sibling* of a shown directory rather than one.
    ///
    /// The rule the sidebar depends on: the app may reveal the project a conversation is
    /// about, not the directory that project happens to sit in.
    #[test]
    fn a_directory_beside_a_shown_one_is_not_shown() {
        let root = workspace("beside");
        let project = root.join("project");
        let sibling = root.join("elsewhere");
        std::fs::create_dir_all(&project).expect("the project");
        std::fs::create_dir_all(&sibling).expect("the sibling");

        let allowlist = Allowlist {
            exports: None,
            workspaces: Vec::new(),
            shown: vec![project.clone()],
        };

        assert!(allowlist.permit(&project.display().to_string()).is_ok());
        assert!(allowlist.permit(&sibling.display().to_string()).is_err());
    }

    /// The export path is the app's, and it is inside the directory the allowlist admits.
    ///
    /// The two facts the export flow exists for: the engine's own default would resolve
    /// `omp-session-<stem>.html` against the *sidecar's* cwd (the user's project), and a
    /// path the app did not choose is a path it cannot promise it may open afterwards.
    #[test]
    fn an_export_is_named_by_the_app_and_lands_where_it_can_be_opened() {
        let exports = Path::new("/config/exports");

        assert_eq!(
            export_path(exports, "01a0bb7d"),
            PathBuf::from("/config/exports/omp-session-01a0bb7d.html")
        );
    }
}
