import {
  ArrowLeft,
  ArrowUp,
  Bell,
  Bot,
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  CodeXml,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  File,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  GripVertical,
  Info,
  Key,
  Keyboard,
  Layers,
  List,
  MessageSquare,
  Minus,
  PanelRight,
  Pencil,
  Pin,
  Play,
  Plug,
  Plus,
  RefreshCw,
  ScrollText,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Terminal,
  Trash2,
  TriangleAlert,
  User,
  WandSparkles,
  Wrench,
  X,
  type LucideIcon,
} from "@lucide/vue";

/**
 * App vocabulary mapped to Lucide's maintained icon set.
 *
 * Keeping this adapter means the rest of the UI talks in stable, semantic names instead of
 * depending on a particular icon package. Swapping a glyph remains a one-line change here.
 */
export const ICONS = {
  search: Search,
  gear: Settings,
  "arrow-left": ArrowLeft,
  keyboard: Keyboard,
  bell: Bell,
  gauge: Gauge,
  bot: Bot,
  layers: Layers,
  brain: Brain,
  wand: WandSparkles,
  plug: Plug,
  code: CodeXml,
  wrench: Wrench,
  scroll: ScrollText,
  key: Key,
  plus: Plus,
  minus: Minus,
  close: X,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  folder: Folder,
  "folder-open": FolderOpen,
  file: File,
  terminal: Terminal,
  panels: PanelRight,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  branch: GitBranch,
  list: List,
  star: Star,
  grip: GripVertical,
  refresh: RefreshCw,
  external: ExternalLink,
  stop: Square,
  "arrow-up": ArrowUp,
  clock: Clock,
  alert: TriangleAlert,
  user: User,
  info: Info,
  download: Download,
  trash: Trash2,
  pencil: Pencil,
  pin: Pin,
  play: Play,
  dots: Ellipsis,
  message: MessageSquare,
  copy: Copy,
} as const satisfies Record<string, LucideIcon>;

/** Every glyph this window can draw. */
export type IconName = keyof typeof ICONS;

/** Glyphs whose app meaning is communicated by a filled state. */
export const SOLID: ReadonlySet<IconName> = new Set(["star", "play", "stop", "pin"]);
